// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu5uPoUrDrHik-VSduhctuZG360NLvKgU',
    appId: '1:1064732291096:web:325778b80bb1d8a99dd36d',
    messagingSenderId: '1064732291096',
    projectId: 'collection-41a91',
    authDomain: 'collection-41a91.firebaseapp.com',
    storageBucket: 'collection-41a91.firebasestorage.app',
    measurementId: 'G-8XGJ2QHL87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl-l4MHfYg5SmsbPAy8J7aDvHQ_2Ao8CQ',
    appId: '1:1064732291096:android:8ccec22aa928125a9dd36d',
    messagingSenderId: '1064732291096',
    projectId: 'collection-41a91',
    storageBucket: 'collection-41a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASYHI94GS3TIbauVDZDzCXd8Jei_lUUKo',
    appId: '1:1064732291096:ios:3d8033c09efc14f89dd36d',
    messagingSenderId: '1064732291096',
    projectId: 'collection-41a91',
    storageBucket: 'collection-41a91.firebasestorage.app',
    iosBundleId: 'app.web.mrCollection',
  );
}
